export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const USERINFO_FAILURE = 'USERINFO_FAILURE'

export const SET_ACCOUNT = 'SET_ACCOUNT'
export const UPDATE_DEVICES = 'UPDATE_DEVICES'

// fabric api
export const GET_CHAIN_SUCC = 'GET_CHAIN_SUCC'
export const GET_BLOCK_SUCC = 'GET_BLOCK_SUCC'

export const GET_PEERS_SUCC = 'GET_PEERS_SUCC'

export const REQUEST_ERR = 'REQUEST_ERR'
